### ISSUE TITLE
precompiled

### ISSUE THREAD

**Issue by cpo81** [GuillaumeLazar/qtrb#4]
Hi, really nice work, Thanks

How to use the pre-compiled zip files?
Is it enough to copy the qtrb_v0.1.img to sd card and the run qmake for the programs on there?
Do you use QT Creator on Ubuntu or something with a remote toolchain?
I don't know how to get started with this.

Thank you very much!

**Comment by GuillaumeLazar** [comment]
Hello, thanks for your message.

Sorry for the poor documentation. This project is really experimental and I can't work as much as I want on it.

I will try to write some documentation on the GitHub wiki page soon.

**Comment by GuillaumeLazar** [comment]
I put some documentation about how to use the pre-compiled zip files on the Wiki.

Check the page [1. How-to-install-a-release?](https://github.com/GuillaumeLazar/qtrb/wiki/1.-How-to-install-a-release%3F)

**Comment by cpo81** [comment]
Wow, thanks for your work.
Can you run qtquick application with qml or just qwidget with it?
In my tests, only qwidget was working.
Error on compiling qtquick application: qtquick module not found.
The Configure output was the same as in your output. It says QtQuick: yes

On 21.03.2018, at 14:26, Guillaume Lazar <notifications@github.com<mailto:notifications@github.com>> wrote:


I put some documentation about how to use the pre-compiles zip files on the Wiki.

Check the page 1. How-to-install-a-release?<https://github.com/GuillaumeLazar/qtrb/wiki/1.-How-to-install-a-release%3F>

**Comment by GuillaumeLazar** [comment]
With the precompiled release v0.1: you can compile and run both "qwidget app" and "qml app".

Can you confirm me something? Are you using the precompiled release v0.1 **OR** do you create it yourself? 

I'm asking it because your issue's label is "precompiled" and your 1st message asking about the precompiled zip files. Now you are talking about "your configure output" (config summary) that only occurs when you compile it yourself. It's confusing for me... :)

Anyway:
- If you want yo use the precompiled release v0.1, you should be fine with qml app: [1. How to install a release?](https://github.com/GuillaumeLazar/qtrb/wiki/1.-How-to-install-a-release%3F)

- If you build it yourself, you must check the complete build log and the generated files [2. How to compile it yourself?](https://github.com/GuillaumeLazar/qtrb/wiki/2.-How-to-compile-it-yourself%3F) 
For example check the presence of Qml libraries (libQt5Quick.so, libQt5Qml, ...) in the directory `/opt/qtrb/qt5pi/lib`.
